# Generated by Django 5.1.7 on 2025-03-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
